heat_template_version: 2016-04-08
description: 'FirstBoot Configuration, multiple'

parameters:
  HostnameMap:
    type: json
    default: {}
    description: Optional mapping to override hostnames
  ControllerHostnameFormat:
    type: string
    default: ""
  ComputeHostnameFormat:
    type: string
    default: ""
  ComputeSriovHostnameFormat:
    type: string
    default: ""
  ComputeDpdkHostnameFormat:
    type: string
    default: ""
  BlockStorageHostnameFormat:
    type: string
    default: ""
  CephStorageHostnameFormat:
    type: string
    default: ""
  ObjectStorageHostnameFormat:
    type: string
    default: ""
  NetworkerHostnameFormat:
    type: string
    default: ""
  ComputeSriovHostIsolatedCoreList:
    type: string
    default: ""
  ComputeSriovKernelArgs:
    type: string
    default: ""
  ComputeDpdkHostIsolatedCoreList:
    type: string
    default: ""
  ComputeDpdkKernelArgs:
    type: string
    default: ""
  ComputeDpdkHostCpusList:
    type: string
    default: ""
    constraints:
      - allowed_pattern: "'[0-9,]+'"
  NeutronDpdkCoreList:
    type: string
    default: ""
  NeutronDpdkSocketMemory:
    type: string
    default: ""
  #
  emc_scaleio_ip1:
    default: ''
    description: IP1 of EMC ScaleIO appliance.
    type: string
  emc_scaleio_ip2:
    default: ''
    description: IP2 of EMC ScaleIO appliance.
    type: string

resources:
  userdata:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: create_log_dir}
      - config: {get_resource: save_hostname_map}
      - config: {get_resource: register_node_role}
      - config: {get_resource: init_disks}
      - config: {get_resource: iscsi_initname}
      - config: {get_resource: controller_fs_mongodb}
      - config: {get_resource: compute_fs_nova}
      - config: {get_resource: install_emc_scaleio}
      - config: {get_resource: computesriov_install_tuned}
      - config: {get_resource: computesriov_kernel_args}
      - config: {get_resource: computedpdk_set_ovs_config}
      - config: {get_resource: computedpdk_set_dpdk_params}
      - config: {get_resource: computedpdk_install_tuned}
      - config: {get_resource: computedpdk_kernel_args}
      - config: {get_resource: encapsulate_rootvol}

  create_log_dir:
    type: OS::Heat::SoftwareConfig
    properties:
      config: {get_file: all-firstboot-config/scripts/create_log_dir.sh}

  save_hostname_map:
    type: OS::Heat::CloudConfig
    depends_on: create_log_dir
    properties:
      cloud_config:
        write_files:
          - path: /var/log/ospd/node_hostnamemap
            content: 
              str_replace:
                template: |
                  _hostnamemap_
                params: 
                  _hostnamemap_: {get_param: HostnameMap}

  register_node_role:
    type: OS::Heat::SoftwareConfig
    depends_on: [ create_log_dir, save_hostname_map ]
    properties:
      group: script
      config:
        str_replace:
          template: {get_file: all-firstboot-config/scripts/register_node_role.sh}
          params:
            _CTRL_FORMAT_ : {get_param: ControllerHostnameFormat}
            _CMPT_FORMAT_ : {get_param: ComputeHostnameFormat}
            _SRIOV_FORMAT_: {get_param: ComputeSriovHostnameFormat}
            _DPDK_FORMAT_ : {get_param: ComputeDpdkHostnameFormat}
            _CNDR_FORMAT_ : {get_param: BlockStorageHostnameFormat}
            _CEPH_FORMAT_ : {get_param: CephStorageHostnameFormat}
            _SWFT_FORMAT_ : {get_param: ObjectStorageHostnameFormat}
            _NETWRK_FORMAT_ : {get_param: NetworkerHostnameFormat}
            _hostnamemap_: {get_param: HostnameMap}

  init_disks:
    type: OS::Heat::SoftwareConfig
    depends_on: register_node_role
    properties:
      config: {get_file: all-firstboot-config/scripts/diskinit.sh}

  iscsi_initname:
    type: OS::Heat::SoftwareConfig
    depends_on: register_node_role
    properties:
      config: {get_file: all-firstboot-config/scripts/iscsi-initname.sh}

  controller_fs_mongodb:
    type: OS::Heat::SoftwareConfig
    depends_on: init_disks
    properties:
      group: script
      config: {get_file: all-firstboot-config/scripts/create_controller_fs_mongodb.sh }

  compute_fs_nova:
    type: OS::Heat::SoftwareConfig
    depends_on: init_disks
    properties:
      group: script
      config: {get_file: all-firstboot-config/scripts/create_compute_fs_nova.sh }

  install_emc_scaleio:
    type: OS::Heat::SoftwareConfig
    depends_on: controller_fs_mongodb
    properties:
      group: script
      config:
        str_replace:
          template: {get_file: all-firstboot-config/scripts/install_emc_scaleio.sh}
          params:
            _EMC_MDMIP1_: {get_param: emc_scaleio_ip1}
            _EMC_MDMIP2_: {get_param: emc_scaleio_ip2}

  computesriov_install_tuned:
    type: OS::Heat::SoftwareConfig
    depends_on: register_node_role
    properties:
      config:
        str_replace:
          template: {get_file: all-firstboot-config/scripts/computesriov_install_tuned.sh}
          params:
            $TUNED_CORES: {get_param: ComputeSriovHostIsolatedCoreList}

  computesriov_kernel_args:
    type: OS::Heat::SoftwareConfig
    depends_on: [ register_node_role, computesriov_install_tuned ]
    properties:
      group: script
      config:
        str_replace:
          template: {get_file: all-firstboot-config/scripts/computesriov_kernel_args.sh}
          params:
            $KERNEL_ARGS: {get_param: ComputeSriovKernelArgs}
            $TUNED_CORES: {get_param: ComputeSriovHostIsolatedCoreList}

  computedpdk_set_ovs_config:
    type: OS::Heat::SoftwareConfig
    depends_on: register_node_role
    properties:
      config: {get_file: all-firstboot-config/scripts/computedpdk_set_ovs_config.sh}

  computedpdk_set_dpdk_params:
    type: OS::Heat::SoftwareConfig
    depends_on: register_node_role
    properties:
      group: script
      config:
        str_replace:
          template: {get_file: all-firstboot-config/scripts/computedpdk_set_dpdk_params.sh}
          params:
            $LCORE_LIST: {get_param: ComputeDpdkHostCpusList}
            $PMD_CORES: {get_param: NeutronDpdkCoreList}
            $SOCKET_MEMORY: {get_param: NeutronDpdkSocketMemory}

  computedpdk_install_tuned:
    type: OS::Heat::SoftwareConfig
    depends_on: register_node_role
    properties:
      group: script
      config:
        str_replace:
          template: {get_file: all-firstboot-config/scripts/computedpdk_install_tuned.sh}
          params:
            $TUNED_CORES: {get_param: ComputeDpdkHostIsolatedCoreList}

  computedpdk_kernel_args:
    type: OS::Heat::SoftwareConfig
    depends_on: [ register_node_role, computedpdk_install_tuned, computedpdk_set_dpdk_params, computedpdk_set_ovs_config ]
    properties:
      group: script
      config:
        str_replace:
          template: {get_file: all-firstboot-config/scripts/computedpdk_kernel_args.sh}
          params:
            $KERNEL_ARGS: {get_param: ComputeDpdkKernelArgs}
            $TUNED_CORES: {get_param: ComputeDpdkHostIsolatedCoreList}

  encapsulate_rootvol:
    type: OS::Heat::SoftwareConfig
    depends_on: [ compute_fs_nova, controller_fs_mongodb, install_emc_scaleio, computesriov_kernel_args, computedpdk_kernel_args ]
    properties:
      config: {get_file: all-firstboot-config/scripts/encapsulate_rootvol.sh}

outputs:
  OS::stack_id:
    value: {get_resource: userdata}
