heat_template_version: 2014-10-16

description: >
  Executes Pre YAML files

parameters:
  server:
    type: string

resources:
  CiscoOpflexComputePreConfig:
    type: /opt/aci-tripleo-patch/puppet/cisco-apic.yaml
    properties:
        server: {get_param: server}

outputs:
  deploy_stdout:
    value:
      list_join:
      - ''
      - - {get_attr: [CiscoOpflexComputePreConfig, deploy_stdout]}
