# Note this can be specified either in the call
# to heat stack-create via an additional -e option
# or via the global environment on the seed in
# /etc/heat/environment.d/default.yaml
parameter_defaults:
  rhel_reg_activation_key: ""
  rhel_reg_base_url: ""
  rhel_reg_environment: ""
  rhel_reg_force: "true"
  rhel_reg_machine_name: ""
  rhel_reg_org: ""
  rhel_reg_password: "MyPassword"
  rhel_reg_pool_id: "8a85f98156sjk"
  rhel_reg_auto_attach: ""
  rhel_reg_release: ""
  rhel_reg_repos: "rhel-7-server-rpms,rhel-7-server-supplementary-rpms,rhel-7-server-optional-rpms,rhel-7-server-extras-rpms,rhel-7-server-openstack-10-rpms,rhel-7-server-openstack-10-tools-rpms,rhel-7-server-openstack-10-optools-rpms,rhel-7-server-openstack-10-devtools-rpms"
  rhel_reg_sat_url: ""
  rhel_reg_server_url: ""
  rhel_reg_service_level: ""
  rhel_reg_user: "user1@redhat.com"
  rhel_reg_type: ""
  rhel_reg_method: "portal"
  rhel_reg_sat_repo: ""
  rhel_reg_http_proxy_host: "squid.redhat.com"
  rhel_reg_http_proxy_port: "3128"
  rhel_reg_http_proxy_username: ""
  rhel_reg_http_proxy_password: ""
