heat_template_version: 2014-10-16

description: >
  Set Keystone authtoken timeout - useful when uploading large glance images

parameters:
  server:
    type: string

resources:
  KeystoneAuthTimeoutConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: scripts/set_keystone_token_expiration.sh}

  KeystoneAuthTimeoutDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config:  {get_resource: KeystoneAuthTimeoutConfig}
      server: {get_param: server}
      actions: ['CREATE','UPDATE'] # do this on CREATE and UPDATE

outputs:
  deploy_stdout:
    description: Deployment reference, used to trigger pre-deploy on changes
    value: {get_attr: [KeystoneAuthTimeoutDeployment, deploy_stdout]}
