heat_template_version: 2014-10-16

description: >
  Configure a specific tuned profile.

parameters:
  server:
    type: string

resources:
  SetupNestedKVMExtraPreConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: scripts/setup_nested_kvm.sh}

  SetupNestedKVMExtraPreDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config: {get_resource: SetupNestedKVMExtraPreConfig}
      server: {get_param: server}
      actions: ['CREATE','UPDATE']

outputs:
  deploy_stdout:
    description: Deployment reference, used to trigger pre-deploy on changes
    value: {get_attr: [SetupNestedKVMExtraPreDeployment, deploy_stdout]}
