heat_template_version: 2014-10-16

description: >
  Configure a specific tuned profile.

parameters:
  server:
    type: string

resources:
  SysctlTunablesExtraPreConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: scripts/sysctl_tunables.sh}

  SysctlTunablesExtraPreDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config: {get_resource: SysctlTunablesExtraPreConfig}
      server: {get_param: server}
      actions: ['CREATE','UPDATE']

outputs:
  deploy_stdout:
    description: Deployment reference, used to trigger pre-deploy on changes
    value: {get_attr: [SysctlTunablesExtraPreDeployment, deploy_stdout]}
