heat_template_version: 2014-10-16

description: >
  Does a global restart of the entire PCS cluster from controller-0

parameters:
  servers:
    type: json

resources:
  DracutRebuildRestartExtraPostConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: scripts/dracut_rebuild.sh}

  DracutRebuildRestartExtraPostDeployment:
    type: OS::Heat::SoftwareDeployments
    properties:
      config: {get_resource: DracutRebuildRestartExtraPostConfig}
      servers: {get_param: servers}
      actions: ['CREATE']
