heat_template_version: 2014-10-16

description: >
  Apply openscap settings to overcloud systems

parameters:
  servers:
    type: json

resources:

  OpenScapConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: scripts/post_deploy-openscap.sh}

  OpenScapDeployment:
    type: OS::Heat::SoftwareDeployments
    properties:
      servers:  {get_param: servers}
      config: {get_resource: OpenScapConfig}
      actions: ['CREATE'] # Only do this on CREATE

