#!/bin/bash
set -x
# yum check-update exits 100 if updates are available
set +e
check_update=$(yum check-update 2>&1)
check_update_exit=$?
set -e
if [[ "$check_update_exit" == "100" ]]; then
    full_command="yum -q -y update"
    echo "Running: $full_command"
    result=$($full_command)
    return_code=$?
    echo "$result"
    echo "yum return code: $return_code"
    exit $return_code
elif [[ "$check_update_exit" == "1" ]]; then
    echo "Failed to check for package updates"
    echo "$check_update"
else
   echo "No packages require updating"
   exit 0
fi
